name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t playstudy-ai .

      - name: Save Docker image
        run: docker save -o playstudy-ai.tar playstudy-ai

      - name: Transfer Docker image to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "File transfer starting..."
          # Use scp to transfer the file
        env:
          TRANSFER_FILE: playstudy-ai.tar
        run: |
          scp -i <(echo "${{ secrets.EC2_SSH_KEY }}") $TRANSFER_FILE ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/

      - name: Deploy Docker image on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop playstudy-ai || true
            docker rm playstudy-ai || true
            docker load -i /home/${{ secrets.EC2_USERNAME }}/playstudy-ai.tar
            docker run -d --name playstudy-ai -p 3000:3000 playstudy-ai